### PR TITLE
catch assistant websocket errors

### LINKED ISSUE #782: Crash during restart in almond-dev
```
Jul 26 23:13:27 crowdie thingengine-child-578[18766]: (node:2) UnhandledPromiseRejectionWarning: Error: WebSocket is not open: readyState 3 (CLOSED)
Jul 26 23:13:27 crowdie thingengine-child-578[18766]:     at WebSocket.send (/opt/thingengine/node_modules/express-ws/node_modules/ws/lib/websocket.js:314:19)
Jul 26 23:13:27 crowdie thingengine-child-578[18766]:     at WebsocketAssistantDelegate.addMessage (/opt/thingengine/routes/my_conversation.js:97:19)
Jul 26 23:13:27 crowdie thingengine-child-578[18766]:     at RpcStub.call (/opt/thingengine/node_modules/transparent-rpc/lib/rpc_socket.js:383:36)
Jul 26 23:13:27 crowdie thingengine-child-578[18766]:     at RpcSocket._handleCall (/opt/thingengine/node_modules/transparent-rpc/lib/rpc_socket.js:251:36)
Jul 26 23:13:27 crowdie thingengine-child-578[18766]:     at RpcSocket._handleMessage (/opt/thingengine/node_modules/transparent-rpc/lib/rpc_socket.js:345:18)
Jul 26 23:13:27 crowdie thingengine-child-578[18766]:     at JsonDatagramSocket.emit (events.js:198:13)
Jul 26 23:13:27 crowdie thingengine-child-578[18766]:     at JsonDatagramSocket._tryReadMessage (/opt/thingengine/util/json_datagram_socket.js:88:18)
Jul 26 23:13:27 crowdie thingengine-child-578[18766]:     at Socket.JsonDatagramSocket.reader.on (/opt/thingengine/util/json_datagram_socket.js:48:18)
Jul 26 23:13:27 crowdie thingengine-child-578[18766]:     at Socket.emit (events.js:198:13)
Jul 26 23:13:27 crowdie thingengine-child-578[18766]:     at addChunk (_stream_readable.js:288:12)
Jul 26 23:13:27 crowdie thingengine-child-578[18766]: (node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
Jul 26 23:13:27 crowdie thingengine-child-578[18766]: (node:2) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

(578 is the anonymous user in almond-dev)

### PR DESCRIPTION
**Pull request by jgd5**
Fixes #782

### CODE REVIEW

File: routes/my_conversation.js [hunk 1]
```diff
@@ -107,11 +107,23 @@ class WebsocketAssistantDelegate {
...
     addMessage(msg) {
-         this._ws.send(JSON.stringify(msg));
+        this._send(JSON.stringify(msg));
+    }
+
+    _send(data) {
+        try {
+            this._ws.send(data);
+        } catch(e) {
+            console.error(`Failed to send error on assistant  websocket: ${e.message}`);
```
Comment (gcampax) [inline routes/my_conversation.js:121]: "Send message" ?

**Review by gcampax — APPROVED** [review]
Yeah
